# Generated by Django 5.1.6 on 2025-05-08 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_address_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_address_set', to='users.address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='identity_document_type',
            field=models.CharField(choices=[('dowod_osobisty', 'Dowód osobisty'), ('prawo_jazdy', 'Prawo jazdy'), ('paszport', 'Paszport'), ('legitymacja_studencka', 'Legitymacja studencka')], max_length=50),
        ),
    ]
