# Generated by Django 5.1.6 on 2025-05-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_date_of_birth_users_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
